### ISSUE TITLE
【react-compiler-babel】示例项目跑不通

### ISSUE THREAD

**Issue by emojiiii** [rspack-contrib/rspack-examples#87]
下载项目后启动出现

window10系统、mac系统都一样

![image](https://github.com/rspack-contrib/rspack-examples/assets/30518686/2b078321-f142-4677-b06e-6317e5303c1f)

**Comment by fi3ework** [comment]
The reason is when using react-compiler as a babel plugin with `@rsbuild/plugin-babel` with a specified `include` or `exclude`. In the final rspack.config.js, the `babel-js` rule will append after the built-in `js` rule, that will make react-compiler not processing the raw source code.

A workaround would be tweaking the rule order as below, not graceful though.
@chenjiahan any suggestion about this?

```diff
export default defineConfig({
  plugins: [
    pluginReact(),
    pluginBabel({
      include: /\.(?:jsx|tsx)$/,
      babelLoaderOptions(opts) {
        opts.plugins?.unshift('babel-plugin-react-compiler')
      },
    }),
  ],
+  tools: {
+    bundlerChain: (chain, { env, CHAIN_ID }) => {
+      chain.module.rule('babel-js').before(CHAIN_ID.RULE.JS)
+    },
+  },
})
```

**Comment by chenjiahan** [comment]
Get, I will fix this in the `@rsbuild/plugin-babel`, we should avoid transforming a JS module twice.
